export enum ActionType {
    AUTHENTICATE_RESPONSE = 'AUTHENTICATE_RESPONSE',
    IS_AUTHENTICATED = 'IS_AUTHENTICATED',

    LOGOUT = 'LOGOUT',
    SET_BIOMETRIC = 'SET_BIOMETRIC',

    REFRESH_TOKEN = 'REFRESH_TOKEN',
    REFRESH_TOKEN_RESPONSE = 'REFRESH_TOKEN_RESPONSE',

    INVALIDATE_TOKEN = 'INVALIDATE_TOKEN',
    REHYDRATE = "persist/REHYDRATE",

}